routes/web.php
<?php

use App\Livewire\HomeComponent;
use App\Livewire\SettingsComponent;
use App\Livewire\UserRegisterComponent;
use App\Livewire\UserRetrievePasswordComponent;
use App\Livewire\CurrenciesComponent;
use App\Livewire\MyCurrenciesComponent;
use App\Livewire\UserLoginComponent;
use App\Http\Controllers\AppController;
use Illuminate\Support\Facades\Route;
use App\Http\Middleware\CustomCheckLoggedInState;
use App\Http\Middleware\RedirectIfAuthenticated;
use App\Http\Middleware\CustomCheckMyCurrenciesRealtionships;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//======= views ========= 
Route::get('/logout', [AppController::class, 'logout'])->name('logout');

//======= we do it components way now ========= 
Route::get('currencies', CurrenciesComponent::class)->middleware(CustomCheckLoggedInState::class)->name('manage-currencies');
Route::get('settings', SettingsComponent::class)->middleware(CustomCheckLoggedInState::class)->name('manage-settings');
Route::get('my-currencies', MyCurrenciesComponent::class)->middleware(CustomCheckLoggedInState::class)->middleware(CustomCheckMyCurrenciesRealtionships::class)->name('my-currencies');
Route::get('login', UserLoginComponent::class)->middleware(RedirectIfAuthenticated::class)->name('login');
Route::get('register', UserRegisterComponent::class)->middleware(RedirectIfAuthenticated::class)->name('register');
Route::get('retrieve-password', UserRetrievePasswordComponent::class)->middleware(RedirectIfAuthenticated::class)->name('retrieve-password');
Route::group(['prefix' => '', 'middleware' => [CustomCheckLoggedInState::class]], function () {
    Route::get('/', HomeComponent::class)->name('landing');
    Route::get('/dashboard', HomeComponent::class)->name('dashboard');
    Route::get('/home', HomeComponent::class)->name('home');
});

app/Livewire/CurrenciesComponent.php
<?php

namespace App\Livewire;

use Livewire\Component;
use App\Models\Currencies as CurrenciesModel;
use Livewire\Attributes\Rule; 
use Livewire\WithPagination; 
use Livewire\Attributes\Computed;

class CurrenciesComponent extends Component
{

    use WithPagination;
    
    #[Rule('required')]
    public $code = "";
    public $description = "";
    public $search = "";

    public $edit_id = "";
    public $modal_title = "";
    public $btn_text = "";
    public $form_action = "";
    public $records_per_page = 10;
    public $page = 1;

    public function mount(){
        $this->get_presets();
    }

    public function render()
    {
        return view('livewire.currencies-component')->layout('livewire.layouts.niceadmin-logged-in');
    }

    public function create()
    {
        $this->validate();
        $insert = ['code' => $this->code, 'description' => $this->description];
        $record = CurrenciesModel::create($insert);
        session()->flash('success-modal','You have added new record successfully.');
        $this->get_presets();
        $this->reset(['code', 'description']);
    }

    public function update()
    {

        $this->validate();
        $update = ['code' => $this->code, 'description' => $this->description];
        CurrenciesModel::where('id',$this->edit_id)->update($update);
        session()->flash('success-modal','You have updated details successfully.');

    }
    
    public function delete($id)
    {
        $record = CurrenciesModel::where('id',$id)->delete();
        $this->get_presets();
        $this->dispatch('close-modal');
        session()->flash('success','You have deleted the record successfully.');
    }

    public function showModal($action, $id = ""){

        $this->get_presets();

        switch($action){
            case 'add': 
                $this->modal_title = "Add New";
                $this->form_action = "create";
                $this->btn_text = "Submit";
                $this->dispatch('show-modal');
                break;
            case 'view':
                $this->form_action = "view";
                $this->modal_title = "View Details";
                $this->set_edit_record($id);
                $this->dispatch('show-modal');
                break;
            case 'edit':
                $this->dispatch('close-modal');
                $this->form_action = "update";
                $this->modal_title = "Update Details";
                $this->btn_text = "Save";
                $this->set_edit_record($id);
                $this->dispatch('show-modal');
                break;
            case 'del':
                $record = CurrenciesModel::where('id', $id)->first();
                $this->edit_id = $record->id;
                $this->dispatch('show-del-modal');
                break;
        }

    }

    function set_edit_record($id){
        $record = CurrenciesModel::where('id', $id)->first();
        $this->edit_id = $record->id;
        $this->code = $record->code;
        $this->description = $record->description;
    }

    #[Computed]
    function records(){
        $filters = [];
        if($this->search != ''){
            $this->resetPage();
            $filters['search'] = $this->search;
        }
        return CurrenciesModel::search($filters)->orderBy('code', 'asc')->orderBy('description', 'asc')->paginate($this->records_per_page);
        // return CurrenciesModel::where('code', 'LIKE', '%' . $filters['search'] . '%')->orderBy('code', 'asc')->orderBy('description', 'asc')->paginate($this->records_per_page);
    }

    function get_presets(){
        $this->records();
    }
}

app/Livewire/HomeComponent.php
<?php

namespace App\Livewire;

use Livewire\Component;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use App\Models\Currencies as CurrenciesModel;
use App\Models\MyCurrencies as MyCurrenciesModel;
use App\Models\Settings as SettingsModel;


class HomeComponent extends Component
{

    public $user = [];
    public $name = "";
    public $currencies = [];
    public $my_currencies = [];

    function mount(){
        $user = Auth::user();
        $this->user = $user;
        $this->name = $user->name;
        $this->currencies = CurrenciesModel::count();
        $this->my_currencies = MyCurrenciesModel::where('user_id', $this->get_user_id())->count();
    }

    public function render()
    {
        return view('livewire.home-component',[
            'user' => $this->user,
        ])->layout('livewire.layouts.niceadmin-logged-in');
    }

    protected $listeners = ['reRenderParent'];
    public function reRenderParent()
    {
        session()->flash('success-modal','You have updated your details successfully.');
        $this->mount();
        $this->render();
    }

    function get_user_id(){
        $user = Auth::user();
        return $user->id;
    }
}

app/Livewire/HomeTabs/HomeTabExchangeCalcComponent.php
<?php

namespace App\Livewire\HomeTabs;

use Livewire\Component;
use Livewire\Attributes\Rule; 
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Helpers\Functions;
use Carbon\Carbon;
use App\Models\User as UserModel;
use App\Models\MyCurrencies as MyCurrenciesModel;
use App\Models\Currencies as CurrenciesModel;
use App\Models\Settings as SettingsModel;
use App\Helpers\CurrencyApiConsumer;

class HomeTabExchangeCalcComponent extends Component
{

    #[Rule('required|numeric')] 
    public $base_amount = "";
    
    #[Reactive] 
    public $my_conversions = [];

    public $base_currency_desc = "";
    public $setting_base_found = true;
    public $base_currency_found = true;
    public $prerequisite_error_msg = "";
    
    public function render()
    {
        return view('livewire.home-tabs.exchange-calc-component', [
            'my_conversions' => $this->my_conversions,
        ]);
    }

    public function boot(){
        // echo "boot";exit;
    }

    function mount(){
        $base_currency = SettingsModel::where('user_id', $this->get_user_id())->where('system_name','base_currency')->first();
        $my_currencies = MyCurrenciesModel::where('user_id', $this->get_user_id())->count();
        if(!$base_currency){
            $this->prerequisite_error_msg = "Please create base currency under <strong>Settings</strong> with: <code>['system_name' => 'base_currency', 'value' => 'ZAR']</code>";
        }elseif($my_currencies == 0){
            $this->prerequisite_error_msg = 'Please load <a href="'.route('my-currencies').'"><strong>My Currencies</strong></a> first.';
        }else{
            $currency = CurrenciesModel::whereRaw('UPPER(code) = ?', strtoupper($base_currency->value))->first();
            if(!$currency){
                $this->base_currency_found = false;
                $this->prerequisite_error_msg = 'Base currency ('.$base_currency->value.') in Settings was not found in at list of <a href="'.route('manage-currencies').'">Manage Currencies</a>.';
            }else{
                $this->base_currency_desc = $currency->code ." (".$currency->description.")";
            }
        }
    }
    
    public function calc_exchange(Request $request)
    {

        $this->validate(); 
        $CurrencyApiConsumer = new CurrencyApiConsumer();
        $base_currency = SettingsModel::where('user_id', $this->get_user_id())->where('system_name','base_currency')->first();
        $my_currencies = MyCurrenciesModel::where('user_id', $this->get_user_id())
        ->orderBy('description', 'asc')
        ->get();
        $my_conversions = [];
        foreach($my_currencies as $line){
            $my_conversions[$line->currency->code] = [
                'amount' => 0,
                'description' => $line->currency->code . ' ('.$line->description.')',
            ];

            $amount = $this->base_amount;
            $from_currency = $line->currency->code;
            $to_currency = $base_currency->value;
            $response = $CurrencyApiConsumer->convert_currency($amount, $from_currency, $to_currency);
            $my_conversions[$line->currency->code] = [
                'amount' => ($response['data']->converted_amount ?? 0),
                'description' => $line->description,
            ];
        }
        ksort($my_conversions);
        $this->my_conversions = $my_conversions;

        //convert_currency($amount, $from_currency, $to_currency)
        /*
        Array
        (
            [status] => 1
            [message] => It worked
            [data] => stdClass Object
                (
                    [date] => 2023-10-25
                    [zar] => 23.13706438
                    [base_amount] => 100
                    [converted_amount] => 2313.71
                    [rate] => 100
                )

        )
        */

    }

    function get_user_id(){
        $user = Auth::user();
        return $user->id;
    }


}

app/Livewire/HomeTabs/HomeTabUpdatePasswordComponent.php
<?php

namespace App\Livewire\HomeTabs;

use Livewire\Component;
use Livewire\Attributes\Rule; 
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Helpers\Functions;
use Carbon\Carbon;
use App\Models\User as UserModel;
use Illuminate\Support\Facades\Hash;
use App\Mail\UserUpdatePasswordMail;
use Illuminate\Support\Facades\Mail;


class HomeTabUpdatePasswordComponent extends Component
{

    #[Rule('required')] 
    public $current_password = "";

    #[Rule('required|max:255')] 
    public $new_password = '';

    #[Rule('required|required_with:new_password|same:new_password|max:255')] 
    public $confirm_password = '';
    
    public function render()
    {
        return view('livewire.home-tabs.update-password-component');
    }
    
    public function update(Request $request)
    {
        $user = Auth::user();
        $this->validate(); 

        $this->validate([
            'current_password' => [
                'required',
                
                function ($attribute, $value, $fail) use ($user) {
                    if (!Hash::check($value, $user->password)) {
                        $fail('Invalid current password');
                    }
                }
            ],
            'new_password' => [
                'required', 'different:current_password'
            ]
        ]);

        UserModel::where('id', $user->id)
        ->update([
           'password' => bcrypt($this->new_password)
        ]);

        $this->send_password_update_email();


        $this->current_password = "";
        $this->new_password = "";
        $this->confirm_password = "";
        session()->flash('success-modal','You have updated your details successfully.');

    }

    function send_password_update_email(){
        //UserUpdatePasswordMail
        $user = Auth::user();
        $name = $user->name;
        $surname = $user->surname;
        $email = $user->email;
        $password = $this->new_password;

        //Send email to this guy with his logins: 
        $recepients_arr[] = ['email' => $email, 'name' => $name." ".$surname];
        $data = [
            'name' => $name,
            'surname' => $surname,
            'email' => $email,
            'password' => $password,
            'login_link' => url('/')."/login",
        ];
        Mail::to($recepients_arr)->send(new UserUpdatePasswordMail($data));

    }


}

app/Livewire/HomeTabs/HomeTabUpdateProfileComponent.php
<?php

namespace App\Livewire\HomeTabs;

use Livewire\Component;
use Livewire\Attributes\Rule; 
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Helpers\Functions;
use Carbon\Carbon;
use App\Models\User as UserModel;
use App\Livewire\HomeComponent;

class HomeTabUpdateProfileComponent extends Component
{

    #[Rule('required')] 
    public $name = "";

    #[Rule('required')] 
    public $surname = "";

    #[Rule('required')]
    public $email = "";

    public function render()
    {
        return view('livewire.home-tabs.update-profile-component');
    }

    function mount(){
        $user = Auth::user();
        $this->name = $user->name;
        $this->surname = $user->surname;
        $this->email = $user->email;
    }
    
    public function update(Request $request)
    {
        $user = Auth::user();
        $this->validate(); 

        //extra validation on email 
        $this->validate([
            'email' => 'unique:users,email,' . $user->id,
        ]);

        UserModel::where('id', $user->id)
        ->update([
           'surname' => $this->surname,
           'name' => $this->name,
           'email' => $this->email,
        ]);
        
        $this->dispatch('reRenderParent')->to(HomeComponent::class);

    }


}

app/Livewire/Layouts/Base.php
<?php

namespace App\Livewire\Layouts;

use Livewire\Component;

class Base extends Component
{
    public function render()
    {
        return view('livewire.layouts.base');
    }
}

app/Livewire/UserLoginComponent.php
<?php

namespace App\Livewire;

use Livewire\Component;
use Livewire\Attributes\Rule; 
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Helpers\Functions;
use Carbon\Carbon;
use App\Models\User as UserModel;

class UserLoginComponent extends Component
{

    #[Rule('required|email')] 
    public $email = '';

    #[Rule('required')] 
    public $password = '';
    public $remember_me = '';

    public function render()
    {
        return view('livewire.user-login-component')->layout('livewire.layouts.niceadmin-logged-out');
    }

    public function login(Request $request)
    {

        $Functions = new Functions();

        $this->validate(); 
        
        $credentials = [
            'email' => $this->email,
            'password' => $this->password,
        ];

        if (Auth::attempt($credentials)) {

            $user = Auth::user();
            $update = ['last_login_at' => Carbon::now()];
            UserModel::where('id',$user->id)->update($update);
            $request->session()->regenerate();
            session()->flash('success','Welcome back ' . $user->name ." " . $user->surname);
            if($Functions->get_login_redirect_url()){
                return redirect($Functions->get_login_redirect_url());
                $Functions->clear_login_redirect_url();
            }else{
                return redirect()->route('home');
            }
        }else{
            session()->flash('danger','Login failed, invalid email and password');
        }

    }
}

app/Livewire/UserRetrievePasswordComponent.php
<?php

namespace App\Livewire;

use Livewire\Component;
use App\Models\User as UserModel;
use Livewire\Attributes\Rule; 
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use Illuminate\Support\Facades\Mail;
use App\Mail\NewUserCreatedMail;

class UserRetrievePasswordComponent extends Component
{

    #[Rule('required|max:255')] 
    public $name = '';

    public function render()
    {
        return view('livewire.user-retrieve-password-component')->layout('livewire.layouts.niceadmin-logged-out');
    }

    public function retreive(Request $request)
    {

        $this->validate(); 
        
    }
    
}

resources/views/livewire/home-component.blade.php
<div>
    @section('title')
        {{ env('APP_NAME') }} | Dashboard
    @endsection

    <div class="pagetitle">
        <h1>Dashboard</h1>
        <nav>
            <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    
    <section class="section profile">
      <div class="row">
        <div class="col-xl-12">

          @include('layouts.alerts.response-modal')

          @include('layouts.alerts.response')
          
          <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
              <ul class="nav nav-tabs nav-tabs-bordered">

                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#dashboard">Dashboard</button>
                </li>
                
                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Edit Profile</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">Change Password</button>
                </li>

              </ul>
              <div class="tab-content pt-2">

              <div class="tab-pane fade show active dashboard" id="dashboard">
                  <div class="row pt-3">
                    <!-- Sales Card -->
                    <div class="col-xxl-6 col-md-6">
                      <div class="card info-card bg-danger text-white">
                        <div class="card-body">
                          <h5 class="card-title">Currencies <span class="text-white">| Today</span></h5>
                          <div class="d-flex align-items-center">
                            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                              <i class="bi bi-currency-exchange"></i>
                              <i class="bi bi-currency-exchange"></i>
                              
                            
                            </div>
                            <div class="ps-3">
                              <h6>{{ $currencies }}</h6>
                              <a href="{{ route('manage-currencies') }}"><span class="text-muted small pt-2 ps-1">View</span></a>
                            </div>
                          </div>
                        </div>

                      </div>
                    </div>
                    <div class="col-xxl-6 col-md-6">
                      <div class="card info-card bg-success text-white">
                        <div class="card-body">
                          <h5 class="card-title">My Currencies <span class="text-white">| Today</span></h5>
                          <div class="d-flex align-items-center">
                            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                              <i class="bi bi-currency-exchange"></i>
                              <i class="bi bi-currency-exchange"></i>
                              
                            
                            </div>
                            <div class="ps-3">
                              <h6>{{ $my_currencies }}</h6>
                              <a href="{{ route('my-currencies') }}"><span class="text-muted small pt-2 ps-1">View</span></a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <!-- Sales Card -->
                    <div class="col-xxl-12 col-md-12">
                      <div class="card info-card bg-dark text-white">
                        <div class="card-body">
                          <h5 class="card-title text-white">Exchange Rate <span>| Today</span></h5>
                          <livewire:home-tabs.home-tab-exchange-calc-component />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="tab-pane fade profile-overview" id="profile-overview">
                    <h5 class="card-title">Profile Details</h5>
                    <hr />
                    <div class="row">
                      <div class="col-lg-3 col-md-4 label ">Full Name</div>
                      <div class="col-lg-9 col-md-8">{{ ucfirst($name) }} {{ ucfirst($user->surname) }} </div>
                    </div>
                    <hr />

                    <div class="row">
                      <div class="col-lg-3 col-md-4 label">Email</div>
                      <div class="col-lg-9 col-md-8">{{ $user->email }}</div>
                    </div>
                    <hr />

                    <div class="row">
                      <div class="col-lg-3 col-md-4 label">Created</div>
                      <div class="col-lg-9 col-md-8">{{ $user->created_at }}</div>
                    </div>
                    <hr />

                    <div class="row">
                      <div class="col-lg-3 col-md-4 label">Last Login</div>
                      <div class="col-lg-9 col-md-8">{{ $user->last_login_at }}</div>
                    </div>

                </div>


                <div class="tab-pane fade profile-edit pt-3" id="profile-edit">
                  <livewire:home-tabs.home-tab-update-profile-component />
                </div>

                <div class="tab-pane fade pt-3" id="profile-change-password">
                  <!-- Change Password Form -->
                  <livewire:home-tabs.home-tab-update-password-component />
                </div>

              </div><!-- End Bordered Tabs -->

            </div>
          </div>

        </div>
      </div>
    </section>
</div>

resources/views/livewire/user-login-component.blade.php
<div>
    @section('title')
        {{ env('APP_NAME') }} | Login
    @endsection
    <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

                <div class="d-flex justify-content-center">
                    <a href="{{ route('login') }}"><img width="250" src="/assets/images/x.png" alt=""></a>
                </div>
                <!-- End Logo -->
                
                <div class="card mb-3">

                    <div class="card-body">

                    <div class="pt-4 pb-2">
                        <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                    </div>

                    @include('layouts.alerts.response')

                    <form class="row g-3" wire:submit="login">

                        <div class="col-12">
                            <label for="yourUsername" class="form-label">Email</label>
                            <div class="input-group has-validation">
                                <span class="input-group-text" id="inputGroupPrepend">@</span>
                                <input autocomplete="off" type="text" name="username" class="form-control" wire:model.blur="email">
                            </div>
                            @error('email')<small class="text-danger">{{ $message }}</small>@enderror 
                        </div>

                        <div class="col-12 mt-2">
                            <label for="yourUsername" class="form-label">Password</label>
                            <div class="input-group has-validation">
                                <span class="input-group-text" id="inputGroupPrepend"><i class="bi bi-unlock"></i></span>
                                <input autocomplete="off" type="password" name="password" class="form-control" wire:model.blur="password">
                            </div>
                            @error('password')<small class="text-danger">{{ $message }}</small>@enderror 
                        </div>

                        <div class="col-12">
                        <div class="form-check">
                            {{-- <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe"> --}}
                            {{-- <label class="form-check-label" for="rememberMe">Remember me</label> --}}
                        </div>
                        </div>
                        <div class="col-12">
                        <button class="btn btn-primary w-100" type="submit">Login</button>
                        </div>
                        <div class="col-12">
                        <p class="small mb-0">Don't have account? <a href="{{ route('register') }}" wire:navigate>Create an account</a></p>
                        </div>
                        <div class="col-12">
                        <p class="small mb-0"><a href="{{ route('retrieve-password') }}" wire:navigate>Retrieve</a> my password I forgot it</p>
                        </div>
                    </form>

                    </div>
                </div>

                <div class="credits">
                    <!-- All the links in the footer should remain intact. -->
                    <!-- You can delete the links only if you purchased the pro version. -->
                    <!-- Licensing information: https://bootstrapmade.com/license/ -->
                    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                    Designed by <a target="_blank" href="http://developerexcuses.com/">Mbusi Lukhele</a>
                </div>

                </div>
            </div>
        </div>
    </section>
</div>

resources/views/livewire/user-retrieve-password-component.blade.php
<div>
    @section('title')
        {{ env('APP_NAME') }} | Retrieve Password
    @endsection
    <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center">
                <a href="{{ route('login') }}"><img width="250" src="/assets/images/x.png" alt=""></a>
              </div>

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Retrieve Password</h5>
                  </div>

                  <form class="row g-3" wire:submit="register">

                      <hr />
                      <div class="row form-group">
                        <div class="col col-md-12">
                            This feature is currently under construction, please search your emails with subject "<strong>New User Created</strong>".
                        </div>
                      </div>
                      <div class="row form-group pt-3">
                        <div class="col col-md-12">
                            You could find your logins on that email.
                        </div>
                      </div>
                      <hr />
                      <div class="col-12">
                        <p class="small mb-0">Found your login details? <a href="{{route('login')}}" wire:navigate>Log in</a></p>
                      </div>
                  </form>

                </div>
              </div>

              <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                Designed by <a target="_blank" href="http://developerexcuses.com/">Mbusi Lukhele</a>
              </div>

            </div>
          </div>
        </div>

      </section>
    </section>
</div>